# Generated by Django 4.1.5 on 2023-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('born', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('fb_link', models.CharField(max_length=255)),
                ('insta_link', models.CharField(max_length=255)),
                ('main_description', models.TextField()),
                ('career_description', models.TextField()),
                ('awards_description', models.TextField()),
                ('image', models.ImageField(upload_to='profile_pics')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
