# Generated by Django 4.1.5 on 2023-02-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_content_blogpost_awards_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
