# Generated by Django 4.1.5 on 2023-02-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_blogpost_fb_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_accepted',
        ),
    ]
