# Generated by Django 4.1.5 on 2023-02-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_blogpost_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='awards_description',
        ),
    ]
