# Generated by Django 4.1.5 on 2023-02-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_blogpost_main_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_description',
            field=models.TextField(),
        ),
    ]
